title: "Mi-Ru Youn"
logo: "/assets/profile.png" # square image
description: >
  Data Science Master's Student at Boston University.<br>
  Experienced in <b>machine learning, reinforcement learning, and data analysis</b>.<br>
  Interested in building <b>AI-driven solutions</b> for research and industry.<br><br>

  <a href="https://linkedin.com/in/miruayoun">LinkedIn</a> |
  <a href="https://github.com/miruyoun">GitHub</a> |
  <a href="/assets/Miru_Youn_Resume.pdf">Resume (PDF)</a><br><br>

  <hr>
  <h3>⚡ Skills</h3>
  <b>Languages:</b> Python, R, SQL, Java, JavaScript, HTML/CSS<br>
  <b>Machine Learning & AI:</b> ML, Deep Learning, Reinforcement Learning, Predictive Analytics<br>
  <b>Frameworks:</b> Scikit-Learn, PyTorch, TensorFlow/Keras, PyTorch Geometric<br>
  <b>Data Tools:</b> Pandas, NumPy, Spark, Hadoop, MongoDB<br>
  <b>Visualization:</b> Matplotlib, Seaborn, Tableau, Power BI<br>
  <b>Platforms:</b><br> Git, Jupyter, AWS, Azure, Linux

theme: jekyll-theme-minimal
google_analytics: UA-000000-0

colors:
  crimson: '#900C3F'
