title: "Mi-Ru Youn"
logo: "/assets/profile.png" # square image
description: >
  Data Science Master's Student at Boston University.  
  Experienced in **machine learning, reinforcement learning, and data analysis**.  
  Interested in building **AI-driven solutions** for research and industry.  

  <a href="https://linkedin.com/in/miruayoun">LinkedIn</a> | 
  <a href="https://github.com/miruyoun">GitHub</a> | 
  <a href="/assets/Miru_Youn_Resume.pdf">Resume (PDF)</a>  

  ---
  ### ⚡ Skills  
  **Languages:** Python, R, SQL, Java, JavaScript, HTML/CSS  
  **Machine Learning & AI:** ML, Deep Learning, Reinforcement Learning, Predictive Analytics  
  **Frameworks:** Scikit-Learn, PyTorch, TensorFlow/Keras, PyTorch Geometric  
  **Data Tools:** Pandas, NumPy, Spark, Hadoop, MongoDB  
  **Visualization:** Matplotlib, Seaborn, Tableau, Power BI  
  **Platforms:** Git, Jupyter, AWS, Azure, Linux

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'